version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      - DB_USER=postgres
#      - DB_PASS=postgres
#      - DB_HOST=db
#      - DB_PORT=5432
#      - DB_NAME=app_db
#
#      - SECRET_KEY=d3e23fdf074b62e9b54985aadeba2ab175c055ab988dcfeb7ae35ead6775febc
#      - TRANSACTION_SECRET_KEY=gfdmhghif38yrf9ew0jkf32
#      - ALGORITHM=HS256
#      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db

volumes:
  postgres_data: